[ui]
force = true
disable = false
port = 8180
interface = "all"
path = "signer"
[rpc]
interface = "all"
apis = ["all"]
hosts = ["all"]
[websockets]
disable = false
port = 8546
origins = ["all"]
interface = "all"
apis = ["all"]
hosts = ["all"]
[ipc]
apis = ["all"]
[dapps]
disable = false
path = "dapps"
[secretstore]
disable = true
path = "secretstore"
[ipfs]
interface = "all"
hosts = ["all"]
[mining]
reseal_min_period = 0
min_gas_price = 0
[footprint]
tracing = "on"
pruning = "archive"
[misc]
logging = "info"